services:
  clientinterface:
    build:
      context: ./ClientInterface
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ClientAPIUrl=http://clientapi/api/
    depends_on:
      - clientapi

  clientapi:
    build:
      context: ./Client.API
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
